/**
 * Copyright 2009 http://anhquan.de
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.04 at 07:33:58 PM CEST 
//


package de.anhquan.codegen.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.anhquan.codegen.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassTable_QNAME = new QName("urn:de:anhquan:codegen:model", "ClassTable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.anhquan.codegen.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassDescriptionType }
     * 
     */
    public ClassDescriptionType createClassDescriptionType() {
        return new ClassDescriptionType();
    }

    /**
     * Create an instance of {@link ClassTableType }
     * 
     */
    public ClassTableType createClassTableType() {
        return new ClassTableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassTableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:de:anhquan:codegen:model", name = "ClassTable")
    public JAXBElement<ClassTableType> createClassTable(ClassTableType value) {
        return new JAXBElement<ClassTableType>(_ClassTable_QNAME, ClassTableType.class, null, value);
    }

}
