//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.10 at 12:15:40 AM CET 
//


package de.anhquan.codegen.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.anhquan.codegen.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassTable_QNAME = new QName("urn:de:anhquan:codegen:model", "ClassTable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.anhquan.codegen.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassDescriptionType }
     * 
     */
    public ClassDescriptionType createClassDescriptionType() {
        return new ClassDescriptionType();
    }

    /**
     * Create an instance of {@link ClassTableType }
     * 
     */
    public ClassTableType createClassTableType() {
        return new ClassTableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassTableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:de:anhquan:codegen:model", name = "ClassTable")
    public JAXBElement<ClassTableType> createClassTable(ClassTableType value) {
        return new JAXBElement<ClassTableType>(_ClassTable_QNAME, ClassTableType.class, null, value);
    }

}
