//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.10 at 12:15:40 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:de:anhquan:codegen:model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.anhquan.codegen.model;
